version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch_hackathon
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      
  neo4j:
    image: neo4j:latest
    container_name: neo4j_hackathon
    environment:
      - NEO4J_AUTH=neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
